name: Create Release
description: "Creates a new release of an iOS framework that is distributed as a binary target via Swift Package Manager"

inputs:
  VERSION_NUMBER:
    description: "The version number of the new release"
    required: true
  XCODE_PROJECT:
    description: "The project to use"
    required: true
  SCHEME:
    description: "The scheme to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: List directory
      shell: sh
      run: "pwd && ls -la"
    - name: Create XCFramework
      shell: sh
      run: "${{ github.action_path }}/xcframework-build.sh -v ${{ inputs.VERSION_NUMBER }} -p ${{ inputs.XCODE_PROJECT }} -s ${{ inputs.SCHEME }}"
    - name: Zip XCFramework
      shell: sh
      run: "zip -r ${{ inputs.XCODE_PROJECT }}.xcframework.zip ./Build/${{ inputs.XCODE_PROJECT }}.xcframework"
    - name: Generate Zip Checksum
      shell: sh
      run: "swift package compute-checksum ${{ inputs.XCODE_PROJECT }}.xcframework.zip > checksum.txt"
    - name: Archive XCFramework.zip
      uses: actions/upload-artifact@v4
      with:
        name: XCFramework-Archive
        path: |
          ./${{ inputs.XCODE_PROJECT }}.xcframework.zip
    - name: Archive Checksum
      uses: actions/upload-artifact@v4
      with:
        name: Checksum
        path: |
          ./checksum.txt