name: XCFramework Build
description: "Creates an XCFramework and saves a zip of it along with a checksum as artifacts"

inputs:
  VERSION_NUMBER:
    description: "The version number of the new release"
    required: true
  XCODE_PROJECT:
    description: "The project to use"
    required: true
  SCHEME:
    description: "The scheme to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create XCFramework
      shell: sh
      run: "${{ github.action_path }}/xcframework-build.sh -v ${{ inputs.VERSION_NUMBER }} -p ${{ inputs.XCODE_PROJECT }} -s ${{ inputs.SCHEME }} -c ${{ github.action_path }}/xcframework-build.xcconfig"
    - name: Zip XCFramework
      shell: sh
      run: "zip -r ${{ inputs.XCODE_PROJECT }}.xcframework.zip ./${{ inputs.XCODE_PROJECT }}.xcframework"
    - name: Generate Zip Checksum
      shell: sh
      run: "swift package compute-checksum ${{ inputs.XCODE_PROJECT }}.xcframework.zip > checksum.txt"
    - name: Archive XCFramework.zip
      uses: actions/upload-artifact@v4
      with:
        name: XCFramework-Archive
        path: |
          ./${{ inputs.XCODE_PROJECT }}.xcframework.zip
    - name: Archive Checksum
      uses: actions/upload-artifact@v4
      with:
        name: Checksum
        path: |
          ./checksum.txt
    - name: Output XCFramework Zip Name
      shell: sh
      run: echo "xcframework-zip-name=${{ inputs.XCODE_PROJECT }}.xcframework.zip" >> "$GITHUB_OUTPUT"