name: XCFramework Build
description: "Creates an XCFramework and saves a zip of it along with a checksum as artifacts"

inputs:
  VERSION_NUMBER:
    description: "The version number of the new release"
    required: true
  XCODE_PROJECT:
    description: "The project to use"
    required: true
  SCHEME:
    description: "The scheme to use"
    required: true
outputs:
  zip_path:
    description: "Path to the zipped XCFramework"

runs:
  using: "composite"
  steps:
    - name: Create XCFramework
      shell: sh
      run: "${{ github.action_path }}/xcframework-build.sh -v ${{ inputs.VERSION_NUMBER }} -p ${{ inputs.XCODE_PROJECT }} -s ${{ inputs.SCHEME }} -c ${{ github.action_path }}/xcframework-build.xcconfig"
    
    - name: Zip XCFramework and Set Output
      shell: sh
      run: |
        zip_name="${{ inputs.XCODE_PROJECT }}.xcframework.zip"
        zip -r "$zip_name" "./${{ inputs.XCODE_PROJECT }}.xcframework"
        echo "zip_path=${zip_name}" >> "$GITHUB_OUTPUT"
    
    - name: Generate Zip Checksum
      shell: sh
      run: "swift package compute-checksum ${{ inputs.XCODE_PROJECT }}.xcframework.zip > checksum.txt"
    
    - name: Archive XCFramework.zip
      uses: actions/upload-artifact@v4
      with:
        name: XCFramework-Archive
        path: |
          ./${{ inputs.XCODE_PROJECT }}.xcframework.zip
    
    - name: Archive Checksum
      uses: actions/upload-artifact@v4
      with:
        name: Checksum
        path: |
          ./checksum.txt